"use client";

import { useState, useEffect, useRef } from "react";

// Shiki highlighter singleton — avoids creating a new instance per CodeBlock
let highlighterInstance: Awaited<ReturnType<typeof import("shiki")["createHighlighter"]>> | null = null;
const loadedLangs = new Set<string>();

async function highlight(code: string, language: string): Promise<string> {
  const shiki = await import("shiki");
  if (!highlighterInstance) {
    highlighterInstance = await shiki.createHighlighter({
      themes: ["github-dark"],
      langs: [language],
    });
    loadedLangs.add(language);
  } else if (!loadedLangs.has(language)) {
    await highlighterInstance.loadLanguage(language as Parameters<typeof highlighterInstance.loadLanguage>[0]);
    loadedLangs.add(language);
  }
  return highlighterInstance.codeToHtml(code, { lang: language, theme: "github-dark" });
}

/**
 * Syntax-highlighted code block using shiki.
 * The HTML output is generated by shiki from developer-provided code strings,
 * not from user input. This is safe to render as raw HTML.
 */
export function CodeBlock({
  code,
  language = "typescript",
  filename,
}: {
  code: string;
  language?: string;
  filename?: string;
}) {
  const [copied, setCopied] = useState(false);
  const [highlightedHtml, setHighlightedHtml] = useState<string>("");
  const copyTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    let cancelled = false;
    highlight(code, language).then((html) => {
      if (!cancelled) setHighlightedHtml(html);
    });
    return () => { cancelled = true; };
  }, [code, language]);

  // Clean up copy timeout on unmount
  useEffect(() => {
    return () => {
      if (copyTimeout.current) clearTimeout(copyTimeout.current);
    };
  }, []);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    if (copyTimeout.current) clearTimeout(copyTimeout.current);
    copyTimeout.current = setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative rounded-[10px] border border-gs-border bg-s1 overflow-hidden glow-border">
      {filename && (
        <div className="flex items-center justify-between px-4 py-2 border-b border-gs-border bg-s2">
          <span className="text-xs font-mono text-dim">{filename}</span>
        </div>
      )}
      <div className="relative">
        {language && (
          <span className="absolute top-3 left-4 text-[10px] font-mono text-dim/50 uppercase tracking-wider">{language}</span>
        )}
        <button
          onClick={handleCopy}
          className="absolute top-3 right-3 text-xs text-dim hover:text-text bg-s2 px-2 py-1 rounded border border-gs-border transition-colors z-10"
        >
          {copied ? (
            <svg className="w-3.5 h-3.5 text-electric" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
          ) : (
            <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" /><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" /></svg>
          )}
        </button>
        <ShikiOutput html={highlightedHtml} fallback={code} />
      </div>
    </div>
  );
}

/** Renders shiki-generated HTML or a plain-text fallback. */
function ShikiOutput({ html, fallback }: { html: string; fallback: string }) {
  if (!html) {
    return (
      <pre className="overflow-x-auto p-4 text-sm font-mono text-text">
        <code>{fallback}</code>
      </pre>
    );
  }

  // SECURITY: shiki output is trusted developer content from static data modules,
  // never from user input. Safe to render as raw HTML.
  // eslint-disable-next-line react/no-danger
  return (
    <div
      className="overflow-x-auto p-4 text-sm [&_pre]:!bg-transparent [&_code]:font-mono"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
