"use client";

import { useState, useEffect } from "react";

/**
 * Syntax-highlighted code block using shiki.
 * The HTML output is generated by shiki from developer-provided code strings,
 * not from user input. This is safe to render as raw HTML.
 */
export function CodeBlock({
  code,
  language = "typescript",
  filename,
}: {
  code: string;
  language?: string;
  filename?: string;
}) {
  const [copied, setCopied] = useState(false);
  const [highlightedHtml, setHighlightedHtml] = useState<string>("");

  useEffect(() => {
    let cancelled = false;
    import("shiki").then(async (shiki) => {
      const highlighter = await shiki.createHighlighter({
        themes: ["github-dark"],
        langs: [language],
      });
      const result = highlighter.codeToHtml(code, {
        lang: language,
        theme: "github-dark",
      });
      if (!cancelled) {
        setHighlightedHtml(result);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [code, language]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative rounded-[10px] border border-gs-border bg-s1 overflow-hidden">
      {filename && (
        <div className="flex items-center justify-between px-4 py-2 border-b border-gs-border bg-s2">
          <span className="text-xs font-mono text-dim">{filename}</span>
        </div>
      )}
      <div className="relative">
        <button
          onClick={handleCopy}
          className="absolute top-3 right-3 text-xs text-dim hover:text-text bg-s2 px-2 py-1 rounded border border-gs-border transition-colors z-10"
        >
          {copied ? "Copied!" : "Copy"}
        </button>
        <ShikiOutput html={highlightedHtml} fallback={code} />
      </div>
    </div>
  );
}

/** Renders shiki-generated HTML or a plain-text fallback. */
function ShikiOutput({ html, fallback }: { html: string; fallback: string }) {
  if (!html) {
    return (
      <pre className="overflow-x-auto p-4 text-sm font-mono text-text">
        <code>{fallback}</code>
      </pre>
    );
  }

  // shiki output is trusted developer content, safe to render
  // eslint-disable-next-line react/no-danger
  return (
    <div
      className="overflow-x-auto p-4 text-sm [&_pre]:!bg-transparent [&_code]:font-mono"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
